###
POST http://localhost:3000/auth/signup

content-type: application/json

{
    "email":"hasib@gmail.com",  
    "password": "hj123456" 
}

###
GET http://localhost:3000/auth/colors/red

###
GET http://localhost:3000/auth/colors